language: ruby
rvm:
- 1.9.3
install: bundle install
before_script:
- npm install -g bower
- bower install
script: bundle exec jekyll build
deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  bucket: victornguyen.net
  local-dir: _site
  acl: public_read
  skip_cleanup: true
  on:
    repo: victornguyen/victornguyen.net