language: ruby
rvm:
  - 2.4.0
install: bundle install
before_script:
  - npm install -g bower
  - bower install
script: bundle exec rake deploy
deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  bucket: vic.codes
  region: ap-southeast-2
  local-dir: _site
  acl: public_read
  skip_cleanup: true
  on:
    branch: master
    repo: victornguyen/vic.codes
notifications:
  slack:
    secure: edSW8rPc6SM/U3A8hCSuT8pVmJE8e4shBon9Zq82Dawuogc4YaZlJytdS4DbN1nR67VGUCsBT+2YPiXgBR35qvaGccNnv3KFoXhehs4V2ybTwldbwCC7lwyFKun7GTd5PpgPAHoTZQeO458AQ8cZBLazt5PY9eCxer9Ptfl7lNq2rav/Jda/74QvOmdlJaWC2NaADqBCaPopMgQhC/gcUmXF0oPb8wRMhTe6aFMNvsRLENh+hDKc2ka1ypmJ7fWvbzl4ng69vD1JgXE1W6yj9C4xskSJCRUfxKf2ev4zSulXnQCzsvahH1MhrQkBUi8p2tUyE4uqx7zRsHLm+YxAdpGqaIfz/GS1QKDp26lebDssPCJTySMri1zEiI4q/zcTWX1WGgoSctd0przgvkF9HJ9K/qmwG5Ly1G7WHdit/q5L0WYQ1K8Mxy/239dCEzCGj14AICkTO+WGFnI5rcAE8eeJwYU6iGH2vhZaR4cnAlAWO08Tjfr+Wy7J2YkbjFbLokTSEFt9wg+oCJYYZAFl8rK640E1XO7NZbutVwv3TRQ07Z+DKXH+GEgNAzY1U3udtaLnOAHgJMIa9G2wOKEPbUWRsgMolUr8IrddJz6HTiQ7pcQ5Z8TffKIQPaQD6PTpNvUpIc2Uz5VfTXgJvXbamicPzr+1c7mGalRT2Do1NSU=
