me:
  name: Victor Nguyen
  email: vic.nguyen@gmail.com
  title: Frontend Developer
  desc: "Victor Nguyen is a pretty good web developer from Melbourne, Australia."

url: https://vic.codes
analytics_id: UA-40566813-1
permalink: /:categories/:title
pygents: true
encoding: utf-8
markdown: kramdown

exclude:
- Rakefile
- vic.codes.sublime-project
- vic.codes.sublime-workspace
- bower.json
- package.json
- node_modules
- Gruntfile.js
- Gemfile
- Gemfile.lock
- assets/bower

gems:
- jekyll-autoprefixer

sass:
  sass_dir: _sass
  style: compressed

autoprefixer:
  browsers:
  - last 2 versions
  - IE > 9
