pygents:        true
permalink:      /:categories/:title
exclude:        ['Rakefile', 'vic.codes.sublime-project', 'vic.codes.sublime-workspace', 'bower.json', 'package.json', 'node_modules', 'Gruntfile.js', 'Gemfile', 'Gemfile.lock']
analytics_id:   UA-40566813-1
encoding:       utf-8
markdown:       kramdown
url:            http://vic.codes

me:
    name:       Victor Nguyen
    email:      vic.nguyen@gmail.com
    title:      Front-end Developer

sass:
    sass_dir:   _sass
    style:      compressed