pygents:        true
permalink:      /:categories/:title
exclude:        ['victornguyen.net.sublime-project', 'victornguyen.net.sublime-workspace', 'component.json']
analytics_id:   UA-40566813-1

me:
    name:       Victor Nguyen
    email:      vic.nguyen@gmail.com
    title:      Frontend Developer